version: '3.0'
services:
    rasa:
        image: rasa/rasa:2.4.1-full
        ports:
            - 5005:5005
        volumes:
            - ./:/ChatbotUni
        command:
            - run
    app:
        image: <image:tag>
        expose: 5055